### ISSUE TITLE
GWT class changes

### ISSUE THREAD

**Issue by jnehlmeier** [Vertispan/gwt-core#2]
Wrong code:
- `GWT.create()` should be static

Missing but required by GWT Widgets / Tests:
- `GWT.isProdMode()`
- `GWT.log(String)`
- `GWT.log(String, Throwable)`
- `GWT.getModuleName()`
- `GWT.getModuleBaseURL()`
- `GWT.setUncaughtExceptionHandler`
Maybe add them here as a reminder that these methods are probably needed. `isProdMode` could be implemented using `superdevmode` property and `GWT.log()` could be replaced with  `java.util.logging` emulation at call sites (or just forward to it within GWT class).

**Comment by niloc132** [comment]
moduleName and moduleBaseURL are probably going to have to be no-op'd, unless we mandate some wrapping code to make a j2cl+closure app "actually gwt". The latter is needed to support things like ClientBundle as well (ping @treblereel) so it knows which directory to read from (and write "artifacts" to...). Standardizing that for "gwt3" _outside_ of gwt-core might make sense, and then have gwt-core either assume the presence of gwt2 _or_ gwt3 wiring to provide that value.

**Comment by jnehlmeier** [comment]
GWT widgets itself actually need `GWT.getModuleBaseURL()` only in a single place for the URL of GWTs `clear.cache.gif` (`ClippedImageImpl`). This could be changed to a ClientBundle URL and then let ClientBundle figure it out. Other than that `FormPanelTest` uses `GWT.getModuleBaseURL()` to post to some servlet.

`GWT.getModuleName()` is used in `FormPanel` to generate an unique form name, even across multiple GWT modules on the same page (something that `Document.get().createUniqueId()` should probably do as well, but currently doesn't)

**Comment by treblereel** [comment]
@niloc132 thank you for mention me, ClientBundle is extremely useful for @jsinterop components, because it's allow us to hide javascript library from end-user and load it transparently. Please keep it in the name of the light

**Comment by niloc132** [comment]
Ok, most of this has been addressed in https://github.com/Vertispan/gwt-core/commit/31c11d093b5624d5a280b9f51ccd5ffb634f48cd and https://github.com/Vertispan/gwt-core/commit/87d30ac958ba9453f425ae2ec4634483877dbd22
 * `log`
 * `isProdMode`
 * `isClient`
 * `isScript`
 * setUncaughtExceptionHandler (hard to test, I did a short manual test once, needs more in depth work)

We can perhaps make a `getModuleBaseURL` (and `getModuleBaseForStaticFiles`...?) by doing what the gwt2 linkers would do and read the actual `script` tag to see where we are attached, but this can be messy. Filed #6 to track this.

Creating a `getModuleName` is less easy, since it implies that there is a module, or a name - neither of those really make sense in gwt3-land as far as I can tell.

Marking closed, please reopen or comment to discuss further if something is missing/broken.
